# Generated by Django 5.0.6 on 2024-06-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=25)),
                ('qualifications', models.CharField(max_length=30)),
                ('teacher_id', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
