# Generated by Django 5.0.6 on 2024-06-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=15)),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('class_teacher', models.CharField(max_length=20)),
                ('number_of_students', models.PositiveSmallIntegerField()),
                ('available_books', models.SmallIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('whiteboard_number', models.PositiveSmallIntegerField()),
                ('number_of_windows', models.PositiveSmallIntegerField()),
                ('arts_number', models.PositiveSmallIntegerField()),
                ('students_nationality', models.CharField(max_length=20)),
            ],
        ),
    ]
